version: "3.8"

services:
  spaniel:
    build:
      context: spaniel
      dockerfile: Dockerfile
    container_name: spaniel_container
    ports:
      - "127.0.0.1:3007:3007"
    depends_on:
      - db_sqlite
    restart: on-failure
    environment:
      TZ: "Europe/Moscow"
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:3007/api/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s
    volumes:
      - ./spaniel/public/temporary:/app/public/temporary
      - ./spaniel/prisma:/app/prisma
      # - prisma_data:/app/prisma # Подключение общего тома

  # SQLite database
  db_sqlite:
    container_name: db_sqlite_container
    image: nouchka/sqlite3
    volumes:
      - ./spaniel/prisma/database-sql-lite.db:/database/database-sql-lite.db
      # - prisma_data:/database  # Подключение общего тома
    stdin_open: true
    tty: true
    working_dir: /database
    entrypoint: ["bash", "-c", "sqlite3 /database-sql-lite.db"]
    healthcheck:
      test: ["CMD-SHELL", "test -f /database/database-sql-lite.db"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s

  # reverse proxy
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./spaniel/public/temporary:/opt/files
      - ./log/report:/opt/report
      - ./.htpasswd:/opt/.htpasswd
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - spaniel
      - db_sqlite
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 5s

# volumes:
#   prisma_data:  # Определение общего тома для prisma
